### ISSUE TITLE
Persist Region between page loads

### ISSUE THREAD

**Issue by pdehaan** [mozilla/ensemble#121]
Per https://github.com/mozilla/ensemble-transposer/issues/57#issuecomment-382542019:

> _"Also, we should probably store the user's preferred category/locale/region in a cookie or localstorage so we can do a "best guess" on their desired category on future page loads (and preload the correct data if they go from _/user-activity_ to _/usage-behavior_) &mdash; but that's probably more of an **ensemble** issue, and not specific to the transposer."_

---

### Steps to reproduce:

1. Go to https://moz-ensemble.herokuapp.com/dashboard/user-activity
1. Set the region to "RU" (Russian).
1. Be amazed at the lovely charts.
1. Click the "Usage Behavior" link at the top-o-the-page.
1. Note the region switches from "RU" to the default "All".

### Expected results:

Persist my desired region between page loads.

### Actual results:

Region is reset to "All" on each new page load.

Not a huge deal, it's just one extra click, but if we do something like https://github.com/mozilla/ensemble-transposer/issues/57 where each region is it's own JSON file (which cuts an unnecessary 90% of the file), it'd potentially save us a network request.

**Comment by openjck** [comment]
Actually, I think I came up with a good version of this using a combination of query parameters, session storage, and custom events. I'll review it with fresh eyes tomorrow and open a PR.

**Comment by openjck** [comment]
Finally have a PR with #222. That was trickier than I thought it would be!

**Comment by openjck** [comment]
I'm going to pause on this for a bit to focus on other, higher-priority tasks.

I ended up using a query parameter to remember the user's region preference. I thought this would make things easier, but it ended up having the opposite effect. It's been *almost done* for a while now, so I think it's time for me to take a break and come back to it in a week or two with fresh eyes. My [progress](https://github.com/openjck/ensemble/commit/6fc6a3cd217089c2b3997f1be58789ae82dd5b93) is pushed to my fork.

When I get back to this, I think I'll try using session storage or local storage exclusively. That should seriously simplify the logic and the tests. Using a query parameter is nice because it allows people to bookmark/share the data at a particular region, but we can always add that after a basic storage-based approach is all set up.

**Comment by openjck** [comment]
I spoke with Davor about this today. He agrees that this is a difficult problem. Storing the region as a query parameter and passing it around to different components requires either sending custom events or using Redux, both of which would increase the complexity of the project. The fact that we also need to store the region preference in localStorage or sessionStorage given that not all pages support regions complicates things even further.

One solution is to hoist a lot of this stuff to the *Application* component, but the downside is that this causes the whole page to re-render, which makes it difficult for users to quickly compare data in different regions.

We decided that we will split this into two tasks: the first is to remember the user's region preference as they browse the site. That's really easy to do, and in fact that's all this issue ever requested. The second piece, which hasn't explicitly been requested here but which would be nice to have, would be to persist the region to a query parameter so that users can bookmark/link to a dashboard in a specific region. We're both interested in how we'll solve that problem but given that this hasn't been requested yet we agreed that we shouldn't block the first piece on the second.
